version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}      
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${DEFAULT_PASSWORD}"
    ports:
      - "54321:80"
    depends_on:
      - postgres